### ISSUE TITLE
Abstract summernote image

### ISSUE THREAD

**Issue by Pierstoval** [Pepsit36/SummernoteBundle#1]
Summernote Image entity should be customizable, and reusable, because sometimes developers implement their own Image entity in order to manage uploads of different kinds.
- Make `SummernoteImage` abstract and ask the user to implement it manually by configuring the class (take FOSUser as example).
- Disable `ApiController` if the image entity has not been loaded (by sending an exception or just showing an error message in the `uploadAction()` method).
- Rename `ApiController` into `ImageUploadController`, because it has only one role (=> [SRP](http://knplabs.com/fr/blog/back-to-basics-solid-single-responsiblity-principle-srp) also talks about naming )

**Comment by Pepsit36** [comment]
- dots 1 and 2: I'm looking to improve this part, it's on the roadmap :)
- dot 3 : ApiController will be not used only for Image Upload, it's why I gave this name, thanks for your link.
